/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pospanbox;

import java.awt.CardLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        proceed = new javax.swing.JButton();
        back = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        salePanel = new javax.swing.JPanel();
        sales = new javax.swing.JButton();
        archery = new javax.swing.JButton();
        orders = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        x = new javax.swing.JLabel();
        salesMainPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        menuPanelOne = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        prcd = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        choicesPanel = new javax.swing.JPanel();
        food = new javax.swing.JButton();
        beverages = new javax.swing.JButton();
        arch = new javax.swing.JButton();
        menuPanelTwo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bck = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        zero = new javax.swing.JButton();
        doubleZero = new javax.swing.JButton();
        dat = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        checkOut = new javax.swing.JButton();
        orderMainPanel = new javax.swing.JPanel();
        onQueue = new javax.swing.JButton();
        finished = new javax.swing.JButton();
        done = new javax.swing.JButton();
        orderPanel = new javax.swing.JPanel();
        orderPanelOne = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        orderPanelTwo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        archryMainPanel = new javax.swing.JPanel();
        finish = new javax.swing.JButton();
        reportMainPanel = new javax.swing.JPanel();
        daily = new javax.swing.JButton();
        weekly = new javax.swing.JButton();
        monthly = new javax.swing.JButton();
        yearly = new javax.swing.JButton();
        reportPanel = new javax.swing.JPanel();
        reportPanelOne = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        reportPanelTwo = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        reportPanelThree = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        reportPanelFour = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setLayout(new java.awt.CardLayout());

        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        label.setText("Sales");
        welcomePanel.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 160, 130, 60));

        welcome.setBackground(new java.awt.Color(255, 255, 255));
        welcome.setFont(new java.awt.Font("HelveticaNeue", 1, 65)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Welcome!");
        welcomePanel.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        proceed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/proceed1.png"))); // NOI18N
        proceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proceedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proceedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proceedMouseExited(evt);
            }
        });
        welcomePanel.add(proceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 150, 50));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/bck1.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        welcomePanel.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 150, 50));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        welcomePanel.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 0, 40, 29));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/main.png"))); // NOI18N
        welcomePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(welcomePanel, "welcomePanel");

        salePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/menu.png"))); // NOI18N
        sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesMouseExited(evt);
            }
        });
        salePanel.add(sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 105, 89));

        archery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/archery.png"))); // NOI18N
        archery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archeryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                archeryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                archeryMouseExited(evt);
            }
        });
        salePanel.add(archery, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 30, 105, 89));

        orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/orders.png"))); // NOI18N
        orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ordersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ordersMouseExited(evt);
            }
        });
        orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersActionPerformed(evt);
            }
        });
        salePanel.add(orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 30, 105, 89));

        reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/reports.png"))); // NOI18N
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        salePanel.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 30, 105, 89));

        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/logout.png"))); // NOI18N
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutMouseExited(evt);
            }
        });
        salePanel.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 30, 75, 89));

        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });
        salePanel.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 0, 40, 29));

        salesMainPanel.setLayout(new java.awt.CardLayout());

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setForeground(new java.awt.Color(255, 255, 255));
        menuPanel.setLayout(new java.awt.CardLayout());

        menuPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        menuPanelOne.setForeground(new java.awt.Color(255, 255, 255));
        menuPanelOne.setPreferredSize(new java.awt.Dimension(1024, 645));
        menuPanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/list.png"))); // NOI18N
        menuPanelOne.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 8, -1, -1));

        prcd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/proceed.png"))); // NOI18N
        prcd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prcdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prcdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prcdMouseExited(evt);
            }
        });
        prcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prcdActionPerformed(evt);
            }
        });
        menuPanelOne.add(prcd, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 530, 189, 95));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/del.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        menuPanelOne.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 530, 88, 95));

        choicesPanel.setBackground(new java.awt.Color(255, 255, 255));
        choicesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        choicesPanel.setForeground(new java.awt.Color(255, 255, 255));
        choicesPanel.setLayout(new java.awt.GridLayout(1, 0));
        menuPanelOne.add(choicesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 10, 625, 620));

        food.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/food.png"))); // NOI18N
        food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                foodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                foodMouseExited(evt);
            }
        });
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });
        menuPanelOne.add(food, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 100));

        beverages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/bvrg.png"))); // NOI18N
        beverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beveragesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                beveragesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                beveragesMouseExited(evt);
            }
        });
        menuPanelOne.add(beverages, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, 100));

        arch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/arch.png"))); // NOI18N
        arch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                archMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                archMouseExited(evt);
            }
        });
        menuPanelOne.add(arch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 100));

        menuPanel.add(menuPanelOne, "menuPanelOne");

        menuPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        menuPanelTwo.setMinimumSize(new java.awt.Dimension(1024, 645));
        menuPanelTwo.setPreferredSize(new java.awt.Dimension(1024, 645));
        menuPanelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/list.png"))); // NOI18N
        menuPanelTwo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 280, 512));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/bck.png"))); // NOI18N
        bck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bckMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bckMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bckMouseExited(evt);
            }
        });
        menuPanelTwo.add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 530, 280, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/tabNum.png"))); // NOI18N
        menuPanelTwo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 10, 350, 170));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/totAmt.png"))); // NOI18N
        menuPanelTwo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 240, 350, 115));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/amtTnrd.png"))); // NOI18N
        menuPanelTwo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 360, 350, 115));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/chgDue.png"))); // NOI18N
        menuPanelTwo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 480, 350, 115));

        zero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/0.png"))); // NOI18N
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                zeroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                zeroMouseExited(evt);
            }
        });
        menuPanelTwo.add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 370, 100, 100));

        doubleZero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/00.png"))); // NOI18N
        doubleZero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doubleZeroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doubleZeroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doubleZeroMouseExited(evt);
            }
        });
        menuPanelTwo.add(doubleZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 370, 100, 100));

        dat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/dat.png"))); // NOI18N
        dat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datMouseExited(evt);
            }
        });
        menuPanelTwo.add(dat, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 370, 100, 100));

        one.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/1.png"))); // NOI18N
        one.setToolTipText("");
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oneMouseExited(evt);
            }
        });
        menuPanelTwo.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 265, 100, 100));

        two.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/2.png"))); // NOI18N
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                twoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                twoMouseExited(evt);
            }
        });
        menuPanelTwo.add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 265, 100, 100));

        three.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/3.png"))); // NOI18N
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                threeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                threeMouseExited(evt);
            }
        });
        menuPanelTwo.add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 265, 100, 100));

        four.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/4.png"))); // NOI18N
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fourMouseExited(evt);
            }
        });
        menuPanelTwo.add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 160, 100, 100));

        five.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/5.png"))); // NOI18N
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fiveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fiveMouseExited(evt);
            }
        });
        menuPanelTwo.add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 160, 100, 100));

        six.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/6.png"))); // NOI18N
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sixMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sixMouseExited(evt);
            }
        });
        menuPanelTwo.add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 160, 100, 100));

        seven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/7.png"))); // NOI18N
        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sevenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sevenMouseExited(evt);
            }
        });
        menuPanelTwo.add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 55, 100, 100));

        eight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/8.png"))); // NOI18N
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eightMouseExited(evt);
            }
        });
        menuPanelTwo.add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 55, 100, 100));

        nine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numPad/9.png"))); // NOI18N
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nineMouseExited(evt);
            }
        });
        menuPanelTwo.add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 55, 100, 100));

        checkOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/chckOut.png"))); // NOI18N
        checkOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkOutMouseExited(evt);
            }
        });
        menuPanelTwo.add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 490, 318, 100));

        menuPanel.add(menuPanelTwo, "menuPanelTwo");

        salesMainPanel.add(menuPanel, "menuPanel");

        orderMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        orderMainPanel.setPreferredSize(new java.awt.Dimension(1024, 645));
        orderMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        onQueue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/onq.png"))); // NOI18N
        onQueue.setToolTipText("");
        onQueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onQueueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onQueueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onQueueMouseExited(evt);
            }
        });
        orderMainPanel.add(onQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 100));

        finished.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/fnshd.png"))); // NOI18N
        finished.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finishedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finishedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                finishedMouseExited(evt);
            }
        });
        orderMainPanel.add(finished, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, 100));

        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/done.png"))); // NOI18N
        done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doneMouseExited(evt);
            }
        });
        orderMainPanel.add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 10, 90, 130));

        orderPanel.setBackground(new java.awt.Color(255, 255, 255));
        orderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        orderPanel.setLayout(new java.awt.CardLayout());

        orderPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        orderPanelOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        orderPanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("On Queue orders");
        orderPanelOne.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        orderPanel.add(orderPanelOne, "orderPanelOne");

        orderPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        orderPanelTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        orderPanelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Finished orders");
        orderPanelTwo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        orderPanel.add(orderPanelTwo, "orderPanelTwo");

        orderMainPanel.add(orderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 10, 815, 631));
        orderPanel.getAccessibleContext().setAccessibleName("");

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/cancel.png"))); // NOI18N
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        orderMainPanel.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 143, 90, 130));

        salesMainPanel.add(orderMainPanel, "orderMainPanel");

        archryMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        archryMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        finish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/finish.png"))); // NOI18N
        finish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finishMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finishMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                finishMouseExited(evt);
            }
        });
        archryMainPanel.add(finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 10, 90, 130));

        salesMainPanel.add(archryMainPanel, "archryMainPanel");

        reportMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        reportMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daily.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/daily.png"))); // NOI18N
        daily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dailyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dailyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dailyMouseExited(evt);
            }
        });
        reportMainPanel.add(daily, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 100));

        weekly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/weekly.png"))); // NOI18N
        weekly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weeklyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                weeklyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                weeklyMouseExited(evt);
            }
        });
        reportMainPanel.add(weekly, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, 100));

        monthly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/monthly.png"))); // NOI18N
        monthly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthlyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monthlyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                monthlyMouseExited(evt);
            }
        });
        reportMainPanel.add(monthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, 100));

        yearly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/yearly.png"))); // NOI18N
        yearly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yearlyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yearlyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yearlyMouseExited(evt);
            }
        });
        reportMainPanel.add(yearly, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 90, 100));

        reportPanel.setBackground(new java.awt.Color(255, 255, 255));
        reportPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportPanel.setLayout(new java.awt.CardLayout());

        reportPanelOne.setBackground(new java.awt.Color(255, 255, 255));
        reportPanelOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportPanelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Daily Report");
        reportPanelOne.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        reportPanel.add(reportPanelOne, "reportPanelOne");

        reportPanelTwo.setBackground(new java.awt.Color(255, 255, 255));
        reportPanelTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportPanelTwo.setPreferredSize(new java.awt.Dimension(1024, 600));
        reportPanelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Weekly report");
        reportPanelTwo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        reportPanel.add(reportPanelTwo, "reportPanelTwo");

        reportPanelThree.setBackground(new java.awt.Color(255, 255, 255));
        reportPanelThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportPanelThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("monthly report");
        reportPanelThree.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        reportPanel.add(reportPanelThree, "reportPanelThree");

        reportPanelFour.setBackground(new java.awt.Color(255, 255, 255));
        reportPanelFour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportPanelFour.setPreferredSize(new java.awt.Dimension(1024, 645));
        reportPanelFour.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("yearly report");
        reportPanelFour.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        reportPanel.add(reportPanelFour, "reportPanelFour");

        reportMainPanel.add(reportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 90, 910, 550));

        salesMainPanel.add(reportMainPanel, "reportMainPanel");

        salePanel.add(salesMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 1024, 640));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/sub.png"))); // NOI18N
        salePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainPanel.add(salePanel, "salePanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clsehvr.png"));
        close.setIcon(ico);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clsehvr.png"));
        close.setIcon(null);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void proceedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/proceed1hvr.png"));
        proceed.setIcon(ico);
    }//GEN-LAST:event_proceedMouseEntered

    private void proceedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/proceed1.png"));
        proceed.setIcon(ico);
    }//GEN-LAST:event_proceedMouseExited

    private void proceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedMouseClicked
        CardLayout sales = (CardLayout) mainPanel.getLayout();
        sales.show(mainPanel, "salePanel");
    }//GEN-LAST:event_proceedMouseClicked

    private void salesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/menuhvr.png"));
        sales.setIcon(ico);
    }//GEN-LAST:event_salesMouseEntered

    private void salesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/menu.png"));
        sales.setIcon(ico);
    }//GEN-LAST:event_salesMouseExited

    private void salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseClicked
        CardLayout sales = (CardLayout) salesMainPanel.getLayout();
        sales.show(salesMainPanel, "menuPanel");
    }//GEN-LAST:event_salesMouseClicked

    private void ordersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/ordershvr.png"));
        orders.setIcon(ico);
    }//GEN-LAST:event_ordersMouseEntered

    private void ordersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/orders.png"));
        orders.setIcon(ico);
    }//GEN-LAST:event_ordersMouseExited

    private void ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersMouseClicked
        CardLayout order = (CardLayout) salesMainPanel.getLayout();
        order.show(salesMainPanel, "orderMainPanel");
    }//GEN-LAST:event_ordersMouseClicked

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/reportshvr.png"));
        reports.setIcon(ico);
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/reports.png"));
        reports.setIcon(ico);
    }//GEN-LAST:event_reportsMouseExited

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
        CardLayout sales = (CardLayout) salesMainPanel.getLayout();
        sales.show(salesMainPanel, "reportMainPanel");
    }//GEN-LAST:event_reportsMouseClicked

    private void logOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/logouthvr.png"));
        logOut.setIcon(ico);
    }//GEN-LAST:event_logOutMouseEntered

    private void logOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/logout.png"));
        logOut.setIcon(ico);
    }//GEN-LAST:event_logOutMouseExited

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutMouseClicked

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clsehvr.png"));
        x.setIcon(ico);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/clse.png"));
        x.setIcon(ico);
    }//GEN-LAST:event_xMouseExited

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        System.exit(0);
    }//GEN-LAST:event_xMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/delhvr.png"));
        delete.setIcon(ico);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/del.png"));
        delete.setIcon(ico);
    }//GEN-LAST:event_deleteMouseExited

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void prcdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prcdMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/proceedhvr.png"));
        prcd.setIcon(ico);
    }//GEN-LAST:event_prcdMouseEntered

    private void prcdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prcdMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/proceed.png"));
        prcd.setIcon(ico);
    }//GEN-LAST:event_prcdMouseExited

    private void prcdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prcdMouseClicked
        CardLayout sales = (CardLayout) menuPanel.getLayout();
        sales.show(menuPanel, "menuPanelTwo");
    }//GEN-LAST:event_prcdMouseClicked

    private void bckMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bckMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/bckhvr.png"));
        bck.setIcon(ico);
    }//GEN-LAST:event_bckMouseEntered

    private void bckMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bckMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/bck.png"));
        bck.setIcon(ico);
    }//GEN-LAST:event_bckMouseExited

    private void bckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bckMouseClicked
        CardLayout sales = (CardLayout) menuPanel.getLayout();
        sales.show(menuPanel, "menuPanelOne");
    }//GEN-LAST:event_bckMouseClicked

    private void zeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/0hvr.png"));
        zero.setIcon(ico);
    }//GEN-LAST:event_zeroMouseEntered

    private void zeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/0.png"));
        zero.setIcon(ico);
    }//GEN-LAST:event_zeroMouseExited

    private void zeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_zeroMouseClicked

    private void doubleZeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doubleZeroMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/00hvr.png"));
        doubleZero.setIcon(ico);
    }//GEN-LAST:event_doubleZeroMouseEntered

    private void doubleZeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doubleZeroMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/00.png"));
        doubleZero.setIcon(ico);
    }//GEN-LAST:event_doubleZeroMouseExited

    private void doubleZeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doubleZeroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_doubleZeroMouseClicked

    private void datMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/dathvr.png"));
        dat.setIcon(ico);
    }//GEN-LAST:event_datMouseEntered

    private void datMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/dat.png"));
        dat.setIcon(ico);
    }//GEN-LAST:event_datMouseExited

    private void datMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_datMouseClicked

    private void oneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/1hvr.png"));
        one.setIcon(ico);
    }//GEN-LAST:event_oneMouseEntered

    private void oneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/1.png"));
        one.setIcon(ico);
    }//GEN-LAST:event_oneMouseExited

    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_oneMouseClicked

    private void twoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/2hvr.png"));
        two.setIcon(ico);
    }//GEN-LAST:event_twoMouseEntered

    private void twoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/2.png"));
        two.setIcon(ico);
    }//GEN-LAST:event_twoMouseExited

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_twoMouseClicked

    private void threeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/3hvr.png"));
        three.setIcon(ico);
    }//GEN-LAST:event_threeMouseEntered

    private void threeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/3.png"));
        three.setIcon(ico);
    }//GEN-LAST:event_threeMouseExited

    private void threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_threeMouseClicked

    private void fourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/4hvr.png"));
        four.setIcon(ico);
    }//GEN-LAST:event_fourMouseEntered

    private void fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fourMouseClicked

    private void fourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/4.png"));
        four.setIcon(ico);
    }//GEN-LAST:event_fourMouseExited

    private void fiveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/5hvr.png"));
        five.setIcon(ico);
    }//GEN-LAST:event_fiveMouseEntered

    private void fiveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/5.png"));
        five.setIcon(ico);
    }//GEN-LAST:event_fiveMouseExited

    private void fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fiveMouseClicked

    private void sixMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/6hvr.png"));
        six.setIcon(ico);
    }//GEN-LAST:event_sixMouseEntered

    private void sixMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/6.png"));
        six.setIcon(ico);
    }//GEN-LAST:event_sixMouseExited

    private void sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sixMouseClicked

    private void sevenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/7hvr.png"));
        seven.setIcon(ico);
    }//GEN-LAST:event_sevenMouseEntered

    private void sevenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/7.png"));
        seven.setIcon(ico);
    }//GEN-LAST:event_sevenMouseExited

    private void sevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sevenMouseClicked

    private void eightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/8hvr.png"));
        eight.setIcon(ico);
    }//GEN-LAST:event_eightMouseEntered

    private void eightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/8.png"));
        eight.setIcon(ico);
    }//GEN-LAST:event_eightMouseExited

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eightMouseClicked

    private void nineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/9hvr.png"));
        nine.setIcon(ico);
    }//GEN-LAST:event_nineMouseEntered

    private void nineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/numPad/9.png"));
        nine.setIcon(ico);
    }//GEN-LAST:event_nineMouseExited

    private void nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nineMouseClicked

    private void checkOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/chckOuthvr.png"));
        checkOut.setIcon(ico);
    }//GEN-LAST:event_checkOutMouseEntered

    private void checkOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/chckOut.png"));
        checkOut.setIcon(ico);
    }//GEN-LAST:event_checkOutMouseExited

    private void checkOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutMouseClicked

    private void prcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prcdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prcdActionPerformed

    private void ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordersActionPerformed

    private void beveragesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beveragesMouseClicked
        CardLayout sales = (CardLayout) choicesPanel.getLayout();
        sales.show(choicesPanel, "beveragesPanel");
    }//GEN-LAST:event_beveragesMouseClicked

    private void foodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMouseClicked
        CardLayout sales = (CardLayout) choicesPanel.getLayout();
        sales.show(choicesPanel, "foodPanel");
    }//GEN-LAST:event_foodMouseClicked

    private void archeryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archeryMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/archeryhvr.png"));
        archery.setIcon(ico);
    }//GEN-LAST:event_archeryMouseEntered

    private void archeryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archeryMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/archery.png"));
        archery.setIcon(ico);
    }//GEN-LAST:event_archeryMouseExited

    private void archeryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archeryMouseClicked
        CardLayout arch = (CardLayout) salesMainPanel.getLayout();
        arch.show(salesMainPanel, "archryMainPanel");
    }//GEN-LAST:event_archeryMouseClicked

    private void foodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/foodhvr.png"));
        food.setIcon(ico);
    }//GEN-LAST:event_foodMouseEntered

    private void foodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/food.png"));
        food.setIcon(ico);
    }//GEN-LAST:event_foodMouseExited

    private void beveragesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beveragesMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/bvrghvr.png"));
        beverages.setIcon(ico);
    }//GEN-LAST:event_beveragesMouseEntered

    private void beveragesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beveragesMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/bvrg.png"));
        beverages.setIcon(ico);
    }//GEN-LAST:event_beveragesMouseExited

    private void archMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/archhvr.png"));
        arch.setIcon(ico);
    }//GEN-LAST:event_archMouseEntered

    private void archMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/arch.png"));
        arch.setIcon(ico);
    }//GEN-LAST:event_archMouseExited

    private void archMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archMouseClicked
        CardLayout sales = (CardLayout) choicesPanel.getLayout();
        sales.show(choicesPanel, "archeryPanel");
    }//GEN-LAST:event_archMouseClicked

    private void onQueueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onQueueMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/onqhvr.png"));
        onQueue.setIcon(ico);
    }//GEN-LAST:event_onQueueMouseEntered

    private void onQueueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onQueueMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/onq.png"));
        onQueue.setIcon(ico);
    }//GEN-LAST:event_onQueueMouseExited

    private void onQueueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onQueueMouseClicked
        CardLayout sales = (CardLayout) orderPanel.getLayout();
        sales.show(orderPanel, "orderPanelOne");
    }//GEN-LAST:event_onQueueMouseClicked

    private void finishedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishedMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/fnshdhvr.png"));
        finished.setIcon(ico);
    }//GEN-LAST:event_finishedMouseEntered

    private void finishedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishedMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/fnshd.png"));
        finished.setIcon(ico);
    }//GEN-LAST:event_finishedMouseExited

    private void finishedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishedMouseClicked
        CardLayout sales = (CardLayout) orderPanel.getLayout();
        sales.show(orderPanel, "orderPanelTwo");
    }//GEN-LAST:event_finishedMouseClicked

    private void doneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/donehvr.png"));
        done.setIcon(ico);
    }//GEN-LAST:event_doneMouseEntered

    private void doneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/done.png"));
        done.setIcon(ico);
    }//GEN-LAST:event_doneMouseExited

    private void doneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_doneMouseClicked

    private void finishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/finishhvr.png"));
        finish.setIcon(ico);
    }//GEN-LAST:event_finishMouseEntered

    private void finishMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/finish.png"));
        finish.setIcon(ico);
    }//GEN-LAST:event_finishMouseExited

    private void finishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_finishMouseClicked

    private void dailyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/dailyhvr.png"));
        daily.setIcon(ico);
    }//GEN-LAST:event_dailyMouseEntered

    private void dailyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/daily.png"));
        daily.setIcon(ico);
    }//GEN-LAST:event_dailyMouseExited

    private void dailyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyMouseClicked
        CardLayout sales = (CardLayout) reportPanel.getLayout();
        sales.show(reportPanel, "reportPanelOne");
    }//GEN-LAST:event_dailyMouseClicked

    private void weeklyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weeklyMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/weeklyhvr.png"));
        weekly.setIcon(ico);
    }//GEN-LAST:event_weeklyMouseEntered

    private void weeklyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weeklyMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/weekly.png"));
        weekly.setIcon(ico);
    }//GEN-LAST:event_weeklyMouseExited

    private void weeklyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weeklyMouseClicked
        CardLayout sales = (CardLayout) reportPanel.getLayout();
        sales.show(reportPanel, "reportPanelTwo");
    }//GEN-LAST:event_weeklyMouseClicked

    private void monthlyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthlyMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/monthlyhvr.png"));
        monthly.setIcon(ico);
    }//GEN-LAST:event_monthlyMouseEntered

    private void monthlyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthlyMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/monthly.png"));
        monthly.setIcon(ico);
    }//GEN-LAST:event_monthlyMouseExited

    private void monthlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthlyMouseClicked
        CardLayout sales = (CardLayout) reportPanel.getLayout();
        sales.show(reportPanel, "reportPanelThree");
    }//GEN-LAST:event_monthlyMouseClicked

    private void yearlyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearlyMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/yearlyhvr.png"));
        yearly.setIcon(ico);
    }//GEN-LAST:event_yearlyMouseEntered

    private void yearlyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearlyMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/yearly.png"));
        yearly.setIcon(ico);
    }//GEN-LAST:event_yearlyMouseExited

    private void yearlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearlyMouseClicked
        CardLayout sales = (CardLayout) reportPanel.getLayout();
        sales.show(reportPanel, "reportPanelFour");
    }//GEN-LAST:event_yearlyMouseClicked

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodActionPerformed

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/bck1.png"));
        back.setIcon(ico);
    }//GEN-LAST:event_backMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/bckhvr1.png"));
        back.setIcon(ico);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/cancelhvr.png"));
        cancel.setIcon(ico);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/buttons/cancel.png"));
        cancel.setIcon(ico);
    }//GEN-LAST:event_cancelMouseExited

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arch;
    private javax.swing.JButton archery;
    private javax.swing.JPanel archryMainPanel;
    private javax.swing.JButton back;
    private javax.swing.JButton bck;
    private javax.swing.JButton beverages;
    private javax.swing.JButton cancel;
    private javax.swing.JButton checkOut;
    private javax.swing.JPanel choicesPanel;
    private javax.swing.JLabel close;
    private javax.swing.JButton daily;
    private javax.swing.JButton dat;
    private javax.swing.JButton delete;
    private javax.swing.JButton done;
    private javax.swing.JButton doubleZero;
    private javax.swing.JButton eight;
    private javax.swing.JButton finish;
    private javax.swing.JButton finished;
    private javax.swing.JButton five;
    private javax.swing.JButton food;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label;
    private javax.swing.JButton logOut;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel menuPanelOne;
    private javax.swing.JPanel menuPanelTwo;
    private javax.swing.JButton monthly;
    private javax.swing.JButton nine;
    private javax.swing.JButton onQueue;
    private javax.swing.JButton one;
    private javax.swing.JPanel orderMainPanel;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JPanel orderPanelOne;
    private javax.swing.JPanel orderPanelTwo;
    private javax.swing.JButton orders;
    private javax.swing.JButton prcd;
    private javax.swing.JButton proceed;
    private javax.swing.JPanel reportMainPanel;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JPanel reportPanelFour;
    private javax.swing.JPanel reportPanelOne;
    private javax.swing.JPanel reportPanelThree;
    private javax.swing.JPanel reportPanelTwo;
    private javax.swing.JButton reports;
    private javax.swing.JPanel salePanel;
    private javax.swing.JButton sales;
    private javax.swing.JPanel salesMainPanel;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton weekly;
    private javax.swing.JLabel welcome;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JLabel x;
    private javax.swing.JButton yearly;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
